export const APP_STRINGS = {
  welcome: {
    badge: "Your smarter study space",
    title: "Turn curiosity into progress.",
    description:
      "Organize what you learn, get clear explanations, and keep every study session moving forward.",
    googleButton: "Continue with Google",
    googleButtonAccessibilityLabel: "Sign in to AI Study Buddy with Google",
    legalPrefix: "By continuing, you agree to keep learning at your own pace.",
    featureFocus: "Focused learning",
    featureAnswers: "Clear answers",
    featureMomentum: "Daily momentum",
  },
  auth: {
    errorTitle: "Could not sign you in",
    errorMessage: "Google Sign-In was not completed. Please try again.",
    missingProvider: "useAuthSession must be used within AuthSessionProvider",
    authenticationRequired: "Authentication is required for this request",
  },
  api: {
    missingBaseUrl: "EXPO_PUBLIC_BASE_URL is not configured",
  },
  drawer: {
    appName: "AI Study Buddy",
    home: "Home",
    newChat: "New chat",
    history: "Recent conversations",
    emailFallback: "Signed in with Google",
    conversations: [
      "Understanding neural networks",
      "Notes from machine learning PDF",
      "Explain retrieval augmented generation",
      "Exam revision plan",
    ],
  },
  chat: {
    title: "What are we learning today?",
    description: "Upload a document and ask questions grounded in your own study material.",
    placeholder: "Ask anything about your document...",
    helper: "AI can make mistakes. Check important answers against your source.",
    uploadAccessibilityLabel: "Upload a document",
    sendAccessibilityLabel: "Send message",
    newChatAccessibilityLabel: "Start a new chat",
    missingProvider: "useChatComposer must be used within ChatComposerProvider",
    acceptedDocumentTypes: ["application/pdf", "text/plain"],
    suggestions: [
      "Summarize this document",
      "Create practice questions",
      "Explain the key concepts",
    ],
  },
  home: {
    eyebrow: "You are signed in",
    defaultName: "Study buddy",
    welcome: (name: string) => `Welcome, ${name}`,
    description: "Your main study workspace is ready for the next feature.",
    signOut: "Sign out",
    signOutAccessibilityLabel: "Sign out of AI Study Buddy",
  },
  symbols: {
    hero: { ios: "brain.head.profile", android: "psychology", web: "psychology" },
    sparkle: { ios: "sparkles", android: "auto_awesome", web: "auto_awesome" },
    book: { ios: "book.closed.fill", android: "menu_book", web: "menu_book" },
    focus: { ios: "scope", android: "filter_center_focus", web: "filter_center_focus" },
    answers: { ios: "lightbulb.max.fill", android: "lightbulb", web: "lightbulb" },
    momentum: { ios: "chart.line.uptrend.xyaxis", android: "trending_up", web: "trending_up" },
    home: { ios: "checkmark.seal.fill", android: "verified", web: "verified" },
    newChat: { ios: "square.and.pencil", android: "edit_square", web: "edit_square" },
    chat: { ios: "bubble.left", android: "chat_bubble_outline", web: "chat_bubble_outline" },
    signOut: { ios: "rectangle.portrait.and.arrow.right", android: "logout", web: "logout" },
    attach: { ios: "paperclip", android: "attach_file", web: "attach_file" },
    document: { ios: "doc.fill", android: "description", web: "description" },
    close: { ios: "xmark", android: "close", web: "close" },
    send: { ios: "arrow.up", android: "arrow_upward", web: "arrow_upward" },
    plus: { ios: "plus", android: "add", web: "add" },
  },
  google: {
    mark: "G",
    webClientId: "autoDetect",
  },
} as const;
