import type { ViewStyle } from "react-native";

export const COLORS = {
  background: "#F7F8FF",
  surface: "#FFFFFF",
  surfaceMuted: "#F0F2FF",
  primary: "#6657E8",
  primaryDark: "#4535C7",
  primarySoft: "#E9E7FF",
  accent: "#FFB84D",
  accentSoft: "#FFF0D7",
  mint: "#35B89A",
  mintSoft: "#DDF7F0",
  textPrimary: "#17162B",
  textSecondary: "#67647A",
  border: "#E5E3F2",
  error: "#C2413B",
  googleBlue: "#4285F4",
  shadow: "#29215C",
  transparent: "transparent",
} as const;

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const RADII = {
  md: 16,
  lg: 24,
  xl: 32,
  pill: 999,
} as const;

export const TYPOGRAPHY = {
  caption: 12,
  body: 16,
  bodyLineHeight: 25,
  button: 16,
  title: 34,
  heroTitle: 42,
  heroLineHeight: 48,
  feature: 13,
  legal: 12,
  letterSpacing: 1.2,
  drawerBrand: 18,
} as const;

export const LAYOUT = {
  flex: 1,
  contentMaxWidth: 560,
  heroHeight: 270,
  heroIconSize: 88,
  heroIconCardSize: 142,
  smallSymbolSize: 20,
  featureIconSize: 18,
  homeIconSize: 54,
  homeIconCardSize: 104,
  googleMarkSize: 24,
  buttonHeight: 58,
  borderWidth: 1,
  decorativeLarge: 190,
  decorativeSmall: 108,
  decorativeOffset: -58,
  pressedScale: 0.985,
  pressedOpacity: 0.72,
  loadingOpacity: 0.68,
  drawerBrandSize: 44,
  drawerBrandIconSize: 25,
  drawerActionIconSize: 20,
  drawerHistoryIconSize: 18,
  drawerHistoryHeight: 44,
  drawerSignOutSize: 38,
  avatarSize: 44,
  chatHeroSize: 96,
  chatHeroIconSize: 52,
  chatDescriptionWidth: 430,
  chatContentWidth: 620,
  composerMaxWidth: 720,
  composerMinHeight: 58,
  composerMaxHeight: 160,
  composerInputMaxHeight: 120,
  composerActionSize: 42,
  composerIconSize: 21,
  composerSmallIconSize: 16,
  documentChipWidth: 300,
  floatingActionSize: 50,
  floatingActionIconSize: 22,
  newChatRowHeight: 44,
  drawerHistoryIconContainer: 34,
  drawerHeaderAvatarSize: 38,
  drawerHeaderActionSize: 38,
  drawerNewChatHeight: 52,
} as const;

export const SHADOWS: Record<"card" | "button", ViewStyle> = {
  card: {
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 7,
  },
  button: {
    shadowColor: COLORS.googleBlue,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 5,
  },
};
